### ISSUE TITLE
[NumberGuesser] Строки

### ISSUE THREAD

**Issue by pavel-b-novikov** [aceisnotmycard/nsudotnet#2]
Вот вы типа литеральные строки используете, все круто так, ага.

А слабо сделать чтобы ругательства были более разнообразные и не строились по принципу UserName + "you are" + фраза, а как-нибудь.. с менее фиксированным порядком слов? Чтобы каждое ругательство было изощренным и издевательским и использовало UserName по-своему.

**Comment by sbogolepov** [comment]
Да, для этого лучше подойдёт обычное форматирование. Пофиксил.
