### ISSUE TITLE
[NumberGuesser] Environment.Exit

### ISSUE THREAD

**Issue by pavel-b-novikov** [aceisnotmycard/nsudotnet#3]
А зачем вам тут Environment.Exit? Чего не return?

Не, не. Вы не торопитесь править. Вы разницу объясните.

**Comment by sbogolepov** [comment]
На MSDN'е написано что различия следующие:
- Exit "убивает" программу из любого места. return – только в том случае, если вызван из Main (или другой точки входа в программу);
- В многопоточной программе Exit убивает программу, не дожидаясь завершения foreground (наверное, правильный перевод на русский язык – "основной") потоков;
- Если вызвать Exit в try или catch блоке, то код в finally вызван не будет;

Таким образом, разницы в данном случае нет.

**Comment by pavel-b-novikov** [comment]
Принято
