### ISSUE TITLE
[LinesCounter] Вопрос на засыпку

### ISSUE THREAD

**Issue by pavel-b-novikov** [aceisnotmycard/nsudotnet#5]
Я вижу кто-то знает LINQ. Точнее, наверняка, не знает.

А ну-ка, что будет если множество files будет пустое? И как заставить LINQ в этом случае вернуть 0? Поверьте, оно вам пригодиться в случае написания запросов к БД.

**Comment by sbogolepov** [comment]
Он и так 0 возвращает же. Даже в документации написано:

> This method returns zero if source contains no elements.

**Comment by pavel-b-novikov** [comment]
В общем короче, мы тут уже с другой студенткой раскурили в чем прикол. В общем не всегда это так. в случае работы с EF и базами данных, этот метод вернет вам очень нелицеприятный Exception. Так что идеологически правильная запись будет files.Select(c=>LinesCoun(c)).DefaultIfEmpty(0).Sum()

Жаль что не получилось продемонстрировать.
