### ISSUE TITLE
[Enigma] Именование, вашу ж машу

### ISSUE THREAD

**Issue by pavel-b-novikov** [aceisnotmycard/nsudotnet#6]
Уберите весь camelCase. Срочно. 

Ну и вдогонку - меня позабавила конструкция:
private const bool EncryptMode = false;
private const bool DecryptMode = !EncryptMode;

Она не критична и если она вам нужна, или  возможно, в ней заключена мудрость предков, помогающая вам решить задачу - оставьте.

**Comment by sbogolepov** [comment]
Больше переменных богу переменных :)
Пофиксил.
